version: '3.7'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: localhost
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - /opt/fastapi_alchemy_asyncs/data:/var/lib/postgresql/data:cached